on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '24 4 * * 1' # Mondays

      - name: Fetch SCA Resolver scan warnings
        id: scaresolver-warnings
        run: |
          scanid=${{ steps.scaresolver.outputs.sca-scan-id }}
          access_token=$(curl -s 'https://platform.checkmarx.net/identity/connect/token' \
              --data-urlencode "username=${{ vars.CHECKMARX_SCA_USERNAME }}" \
              --data-urlencode "password=${{ secrets.CHECKMARX_SCA_PASSWORD }}" \
              --data-urlencode "acr_values=Tenant:${{ vars.CHECKMARX_SCA_TENANT }}" \
              --data-urlencode "scope=sca_api" \
              --data-urlencode "client_id=sca_resource_owner" \
              --data-urlencode "grant_type=password" | jq -r '.access_token')

          if [ -z "$access_token" ];then
            echo "Failed to fetch access token"
            exit 1
          fi
          curl -s -X GET https://api-sca.checkmarx.net/risk-management/projects -H "Authorization: bearer $access_token" \
            | jq -r '.[] | select(.name|test("retentionscience")) | "\(.name) \(.latestScanId)"' \
            | while read project scanid;do
                curl -s https://api-sca.checkmarx.net/risk-management/riskReports/$scanid/warnings -H "Authorization: bearer $access_token" \
                  | jq --arg project "$project" --arg scanId "$scanid" '.[] += $ARGS.named | .[]'
              done | jq --slurp > sca-warnings.json

    - name: Upload SCA warnings 
      uses: actions/upload-artifact@v3
      with:
          name: sca-warnings.json
          path: sca-warnings.json
